version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product_registry
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  registry1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: registry/build/libs/registry.jar
        UTIL_DIR: run/
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - WAIT_FOR_IT=db:5432
      - JAVA_OPTS=-Xmx512m -Xms256m

volumes:
  db:
    driver: local